//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Suppliers.Data
{
    public partial class ContentBudgetCostLink
    {
        public int ContentId { get; set; }
        public int DataContentId { get; set; }
        public double ContentAllocation { get; set; }
        public bool Active { get; set; }
        public int InsertUserId { get; set; }
        public int UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Content Content { get; set; }
    }
    
}
